# Generated by Django 4.1.7 on 2023-04-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
